public class Cloudinary_Constants {
     
    //Method Type
    public static final String METHOD_TYPE_GET = 'GET';  
    public static final String METHOD_TYPE_POST = 'POST';  
    public static final String METHOD_TYPE_PUT = 'PUT';  
    public static final String METHOD_TYPE_DELETE = 'DELETE';  
    
    //Error Messages
    public static final String ENDPOINT_NOT_FOUND = 'Endpoint Not Found';
    
    //Endpoints
    public static final String ENDPOINT_DEVELOPER_NAME_UPLAOD_IMAGE_API = 'UplaodImageApi';
    public static final String ENDPOINT_DEVELOPER_NAME_RESOURCE_API = 'ResourceApi';
    
    //for http req 
    public static final String ACCEPT_HEADER = 'application/json';
    public static final String CONTENT_TYPE_HEADER = 'application/json';
}